from pydantic import BaseModel, Field
from typing import List

# Define the structure for a single element as generated by the LLM
class LLMElement(BaseModel):
    """The refined element list produced by the LLM analysis."""
    element_id: str = Field(..., pattern=r"^\w+-\d+$", description="Unique ID generated by PageExplorer: e.g., button-5, link-12.")
    tag: str = Field(..., description="HTML tag name, e.g., 'input', 'button', 'a'.")
    text_content: str = Field(..., description="The visible text content of the element or its accessible name.")
    role: str = Field(..., description="The semantic role of the element, e.g., 'username_input', 'search_button', 'forgot_password_link'.")

# Define the final expected response structure from the LLM
class StructuredRepresentation(BaseModel):
    """The top-level structure for the LLM's refined element list."""
    elements: List[LLMElement] = Field(..., description="A list of interactive elements found and analyzed.")